import test from "node:test";

import { FixtureRunner } from "@gmloop/fixture-runner";

import { createFixtureSuiteRegistry } from "./fixture-suite-registry.js";

/**
 * Runs one batch of cross-module integration fixture cases in a dedicated
 * process, driven by {@link ../cross-module-integration.test.ts}.
 *
 * The GML grammar automaton generated by ANTLR shares its SLL prediction
 * caches across every recognizer instance in a process (see
 * `src/parser/src/gml-parser.ts`). Running all ~20 integration fixtures --
 * each exercising distinct, unrelated GML syntax -- through that one shared
 * automaton lets the cache accumulate enough divergent prediction state that
 * an unlucky later fixture can pay a catastrophic (60s+) SLL/LL negotiation
 * cost. Splitting the fixtures into small batches, each executed by a fresh
 * process with its own untouched automaton, keeps every fixture on the fast
 * path without weakening what the suite verifies.
 */
void test("cross-module integration fixture batch runs successfully", async () => {
    const caseIdsJson = process.env.GMLOOP_INTEGRATION_FIXTURE_BATCH_CASE_IDS_JSON;
    if (!caseIdsJson) {
        throw new Error("Missing required environment variable GMLOOP_INTEGRATION_FIXTURE_BATCH_CASE_IDS_JSON.");
    }

    const caseIds = JSON.parse(caseIdsJson) as unknown;
    if (!Array.isArray(caseIds) || caseIds.some((caseId) => typeof caseId !== "string")) {
        throw new Error("GMLOOP_INTEGRATION_FIXTURE_BATCH_CASE_IDS_JSON must be a JSON array of strings.");
    }

    const fixtureSuite = createFixtureSuiteRegistry().find((suite) => suite.workspaceName === "integration");
    if (!fixtureSuite) {
        throw new Error("Unable to locate the integration fixture suite registration.");
    }

    const runResult = await FixtureRunner.runFixtureSuite({
        fixtureRoot: fixtureSuite.fixtureRoot,
        adapter: fixtureSuite.adapter,
        caseIds: caseIds as Array<string>
    });

    if (runResult.failures.length > 0) {
        const failureSummaries = runResult.failures.map((failure) => {
            const message = failure.error instanceof Error ? failure.error.message : JSON.stringify(failure.error);
            return `${failure.fixtureCase.caseId}: ${message}`;
        });
        throw new Error(
            `Integration fixture batch failed for ${runResult.failures.length} case(s):\n- ${failureSummaries.join("\n- ")}`
        );
    }
});
